### ISSUE TITLE
Windows ?

### ISSUE THREAD

**Issue by ghost** [dskinner/snd#2]
Have you tried on with does 10 ?

**Comment by dskinner** [comment]
Whether it works on windows would depend on if openal via golang.org/x/mobile works on windows at the moment, and I don't believe this is yet the case (but I may be mistaken).

Never the less, there isn't a great deal of work to support additional drivers if there's a binding or implementation for Direct Sound. It would be done like: https://github.com/dskinner/snd/blob/master/al/al.go

But many of these have different options (consider JACK on linux), so I haven't distilled a common interface for connecting and starting audio yet, only separate packages.

**Comment by ghost** [comment]
hey - thanks for thorough comment.

I shoudl test it on windows i guess :)

bummer about windows 10. The reason i asked is because i am using this:
https://github.com/andlabs/ui
Its really cool, but i need sound too..

**Comment by ghost** [comment]
@dskinner 
i just tried to go get from windows 10 but for some reason it complains.. 
on osx its fine.

any ideas ?
i am using go 1.71

```

go get dasa.cc/snd
package dasa.cc/snd: unrecognized import path "dasa.cc/snd" (https fetch: Get https://dasa.cc/snd?go-get=1: net/http: TLS handshake timeout)

```

**Comment by dskinner** [comment]
Yikes! thanks for reporting. I appear to be having some sort of domain issue. In the interim until I resolve:

```
mkdir -p $GOPATH/src/dasa.cc
git clone https://github.com/dskinner/snd.git $GOPATH/src/dasa.cc/snd
```

**Comment by ghost** [comment]
i tried that :) Its not feasible; too many sub dependencies further down like your material repo that use these custom URLS

best if you let me knwo when your custom URLS are working, rather than me messing around

**Comment by dskinner** [comment]
ah, indeed. I can't guarantee the piano demo depending on material will run though. I still have a number of changes related to text and general image output that needs to get pushed.

I fixed the issue I was having so `go get` should work now.

**Comment by ghost** [comment]
Just so you know the dasa.cc/snd import path is still failing with `go get` due to a `TLS handshake timeout`

**Comment by dskinner** [comment]
VM was hanging, should be working now. I need to do something more reliable, clearly.

**Comment by ghost** [comment]
Thanks :)
